chore: Rename the Terraform workflow file steps (#30)
Signed-off-by: gatici <gulsum.atici@canonical.com>

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -1,28 +1,38 @@
-name: Check the Terraform Module
+# Copyright 2024 Canonical Ltd.
+# See LICENSE file for licensing details.
+
+name: Check Terraform Module
 
 on:
   workflow_call:
 
 jobs:
-  build:
-    name: Terraform Checks and Plans
+  check-terraform:
+    name: Check Terraform
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: ./terraform
+
     steps:
-      - name: Checkout the repository to the runner
+      - name: Checkout Repository
         uses: actions/checkout@v4
 
-      - name: HashiCorp - Setup Terraform
+      - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
 
-      - name: Terraform Format
-        id: fmt
-        run: terraform fmt -recursive -check
-        continue-on-error: true
-
-      - name: Terraform Init
-        id: init
+      - name: Initialize Terraform Module
         run: terraform init
 
-      - name: Terraform Validate
-        id: validate
+      - name: Validate Terraform Module
         run: terraform validate -no-color
+
+      - name: Validate terraform fmt
+        run: |
+          set +e 
+          terraform fmt -recursive -check -diff
+          FMT_STATUS="$?"
+          if [[ "$FMT_STATUS" -ne 0 ]]; then
+            echo "❌ terraform fmt failed" >> "$GITHUB_STEP_SUMMARY"
+          fi
+          exit "$FMT_STATUS"
